image: "docker:20.10.16"

variables:
  DOCKER_TLS_CERTDIR: "/certs"

services:
  - docker:20.10.16-dind
  

stages:

  - Deploy





deploy 3.0:
  stage: Deploy
  
  before_script: 
      - mkdir -p ~/.ssh
      - echo -e "$MSDATDEVELOP" > ~/.ssh/id_rsa
      - chmod 600 ~/.ssh/id_rsa
      - '[[ -f /.dockerenv ]] && echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config'
  script:
    - ssh -p3322 e4esysadmin@208.87.128.190 "cd /srv/msdat3.0/msdat/  && git pull origin staging && docker-compose up -d --build && docker ps "
  only:
    - staging
  

