image: node:16-alpine

stages:
  - build
  - deploy

# --------------------
# CACHE (speed boost)
# --------------------
cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - node_modules/

# --------------------
# BUILD (develop)
# --------------------
build_develop:
  stage: build
  only:
    - develop
  script:
    - test -f "$staging_env"
    - cp "$staging_env" .env
    - yarn install --frozen-lockfile
    - yarn build
    - yarn docs:build || true
  artifacts:
    paths:
      - dist/
      - docs/.vuepress/dist/
    expire_in: 1h

# --------------------
# DEPLOY (develop)
# --------------------
deploy_develop:
  stage: deploy
  only:
    - develop
  dependencies:
    - build_develop
  before_script:
    - apk add --no-cache rsync openssh
    - mkdir -p ~/.ssh
    - echo "$MSDATDEVELOP" > ~/.ssh/id_rsa
    - chmod 600 ~/.ssh/id_rsa
    - '[[ -f /.dockerenv ]] && echo -e "Host *\n\tStrictHostKeyChecking no\n" > ~/.ssh/config'
  script:
    - rsync -avz --delete -e "ssh -p 3322" dist/ e4esysadmin@208.87.128.190:/srv/msdat/dist/
    - rsync -avz --delete -e "ssh -p 3322" docs/.vuepress/dist/ e4esysadmin@208.87.128.190:/srv/msdat/docs/ || true
    - ssh -p3322 e4esysadmin@208.87.128.190 "pm2 reload msdat"

build_master:
  stage: build
  only:
    - master
  script:
    - test -f "$master_env"
    - cp "$master_env" .env
    - yarn install --frozen-lockfile
    - yarn build
  artifacts:
    paths:
      - dist/
    expire_in: 1h

deploy_master:
  stage: deploy
  only:
    - master
  when: manual
  dependencies:
    - build_master
  before_script:
    - apk add --no-cache rsync openssh
    - mkdir -p ~/.ssh
    - echo "$MSDATMASTER" > ~/.ssh/id_rsa
    - chmod 600 ~/.ssh/id_rsa
    - '[[ -f /.dockerenv ]] && echo -e "Host *\n\tStrictHostKeyChecking no\n" > ~/.ssh/config'
  script:
    - rsync -avz --delete -e "ssh -p 3322" dist/ e4esysadmin@172.93.48.4:/srv/msdat/dist/
    - ssh -p3322 e4esysadmin@172.93.48.4 "sudo cp -r /var/www/msdat-dashboard/dist/covid* /srv/msdat/dist/"
