export default {
  getDashboard: 'dashboards/',
  getDataSource: 'datasources/',
  getLocation: 'location/',
  getIndicator: 'indicators/',
  getLHL: 'location_hierarchy_level/',
  getValueType: 'valuetypes/',
  getLinks: 'links/',
  getFactors: 'factors/',
  getDSI: 'datasource_specific_indicator/',
  getData: 'data/',
  getLastUpdated: 'data/latest/',
  getUpdatedDataDate: 'data/after_datetime/',
  getNhmisMonthly: `data/?datasource=${33}`,
};
