export default {
  getDashboard: 'dashboards/?size=20',
  getDataSource: 'datasources/?size=1000',
  getLocation: 'location/?size=1000',
  getIndicator: 'indicators/?size=1000',
  getLHL: 'location_hierarchy_level/?size=1000',
  getValueType: 'valuetypes/?size=1000',
  getLinks: 'links/?size=1000',
  getFactors: 'factors',
  getDSI: 'datasource_specific_indicator/?size=1000',
  // getData: 'http://209.182.232.228:7000/api/crud/data',
  getData: 'data/',
  // getLastUpdated: 'data/latest/?size=1000',
  getUpdatedDataDate: 'data/after_datetime/?size=1000',
};
